"use client";
import { useState } from "react";
import type { ClassificationResult } from "@/modules/classification/schema";
import type { RoutingDecision } from "@/modules/routing/decide-route";
type Evidence = ReadonlyArray<{ readonly label: string; readonly value: string; readonly status: string }>;

export function OperatorConsole({ classification: c, evidence, decision }: { classification: ClassificationResult; evidence: Evidence; decision: RoutingDecision }) {
  const [assigned, setAssigned] = useState(false), [takeover, setTakeover] = useState(false), [reviewed, setReviewed] = useState(false), [approved, setApproved] = useState(false);
  const [audit, setAudit] = useState(["ROUTING_DECIDED", "LEDGER_LOOKUP", "DRAFT_CREATED"]);
  const log = (event: string) => setAudit((items) => [event, ...items]);
  const fields = [["의도", c.intent], ["생활 영역", c.domain], ["심각도", c.severity], ["긴급도", c.urgency], ["방향", c.direction], ["개입 희망", c.interventionPreference]];
  return <div className="shell">
    <aside className="sidebar"><div className="brand"><span>HT</span><b>HOME<br />TOGETHER</b></div><p className="sideLabel">OPERATIONS</p><nav>{["⌁　이슈 큐", "▣　정기 체크인", "≡　가구 원장", "◇　질문 은행", "⌕　지식 백로그"].map((item, i) => <button className={i === 0 ? "active" : ""} key={item}>{item}{i === 0 && <i>1</i>}</button>)}</nav><div className="safety"><em /><p><b>Human review on</b><small>자동 발송 · 자동 중재 꺼짐</small></p></div></aside>
    <main><header><p><span>거주 라우터　/　</span><b>이슈 상세</b></p><em>V0 · DEMO</em></header><section className="notice"><b>!</b><p><strong>가상 데이터 번들이 연결되지 않았습니다.</strong> 명세의 HH-002 소음 시나리오만 재현합니다.</p></section>
      <section className="pageHead"><div><p className="kicker">ISSUE / HH-002 / NOISE</p><h1>밤마다 TV 소리가 커서<br />잠을 못 자겠어요.</h1><p className="meta">●　당일 확인 필요 · 인바운드 접수</p></div><div className="actions"><button className="secondary" onClick={() => { setTakeover(!takeover); log(takeover ? "HUMAN_TAKEOVER_ENDED" : "HUMAN_TAKEOVER_STARTED"); }}>{takeover ? "상담 종료" : "상담원 전환"}</button><button className="primary" onClick={() => { if (!assigned) log("ISSUE_ASSIGNED"); setAssigned(true); }}>{assigned ? "김다은에게 배정됨" : "내게 배정"}</button></div></section>
      <section className="route"><b>{decision.route}</b><div><small>ROUTE DECISION</small><strong>사람에게 연결</strong></div><p>{c.reasonCodes.map((r) => <span key={r}>{r}</span>)}</p><div><small>SLA</small><strong>오늘 18:00</strong></div></section>
      <div className="workspace"><section className="mainColumn"><article className="card"><div className="cardHead"><b>게스트 원문</b><small>KAKAO · MESSAGE</small></div><blockquote>“요즘 밤마다 TV 소리가 커서 잠을 못 자겠어요.<br />직접 말씀드리기는 좀 그래요.”</blockquote><p className="privacy">●　원문은 상대방에게 그대로 전달되지 않습니다.</p></article>
        <article className="card"><div className="cardHead"><b>구조화 분류</b><small>SCHEMA VALID · CONFIDENCE {c.confidence * 100}%</small></div><div className="classify">{fields.map(([label, value]) => <div key={label}><small>{label}</small><b>{value}</b></div>)}</div><div className="signal"><small>언어적 신호</small><b>{c.distressSignal}</b><span>“잠을 못 자겠어요”, “직접 말씀드리기는 좀 그래요”</span></div></article>
        <article className="card"><div className="cardHead"><b>가구 원장 대조</b><small>✓ HOUSEHOLD ISOLATED</small></div><div className="ledger">{evidence.map((e) => <div key={e.label}><small>{e.label}</small><b>{e.value}</b><em>{e.status}</em></div>)}</div><p className="grounding">✓　확정 조항이 없어 A갈래 자동 답변을 중단하고 B갈래로 전환했습니다.</p></article>
        <article className="card"><div className="cardHead"><b>운영자 코파일럿</b><small>{approved ? "OPERATOR APPROVED · NOT SENT" : "DRAFT · 고객에게 미발송"}</small></div><label className="draft"><small>첫 회신 초안</small><textarea readOnly={approved} defaultValue="말씀해 주셔서 감사해요. 답변 내용은 상대방께 그대로 전달되지 않습니다. 필요한 내용만 정리해 오늘 중 담당자가 연락드릴게요." /></label><div className="guards"><p><small>전달할 핵심</small>야간 TV 사용 시간과 이후 이어폰 사용 기준 조율</p><p><small>금지</small>잘못 판단 · 원문 전달 · 합의되지 않은 시간 단정</p></div><div className="approval"><label><input type="checkbox" checked={reviewed} onChange={(e) => setReviewed(e.target.checked)} /> 원문·근거·금지 문구를 확인했습니다.</label><button className="primary" disabled={!reviewed || approved} onClick={() => { setApproved(true); log("DRAFT_APPROVED_NOT_SENT"); }}>초안 {approved ? "승인 완료" : "승인"}</button></div></article></section>
        <aside className="rightColumn"><article className="card"><p className="kicker">HOUSEHOLD</p><h2>HH-002</h2><dl><div><dt>현재 상태</dt><dd>거주 중</dd></div><div><dt>미해결 이슈</dt><dd>1건</dd></div><div><dt>최근 체크인</dt><dd>데이터 없음</dd></div></dl></article><article className="card"><div className="cardHead"><b>감사 로그</b><small>{audit.length}</small></div><ul>{audit.map((item, i) => <li key={`${item}-${i}`}><b>{item}</b><small>{i === 0 ? "operator action" : "recorded"}</small></li>)}</ul></article></aside></div>
    </main></div>;
}
